# Generated by Django 3.0.3 on 2020-02-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=280)),
                ('user_posted', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
