# Generated by Django 3.0.3 on 2020-03-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
