# Generated by Django 3.0.3 on 2020-03-29 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_posttemp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
