# Generated by Django 3.0.3 on 2020-03-29 19:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTemp',
            new_name='Post',
        ),
    ]
